name: Release
on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: "386"
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          GOARM: ${{ matrix.goarm || '' }}
        run: |
          mkdir -p build
          if [ "${GOARCH}" = "arm" ]; then
            go build -o build/OpenGFW-${GOOS}-${GOARCH}v${GOARM} -ldflags "-s -w" .
          else
            go build -o build/OpenGFW-${GOOS}-${GOARCH} -ldflags "-s -w" .
          fi

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
